services:
  - type: web
    name: voice-bbs
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        value: bubblevoice.onrender.com
