services:
  - type: web
    name: voice-bbs
    env: elixir
    region: singapore
    plan: free
    buildCommand: mix deps.get && mix assets.setup && mix assets.deploy
    startCommand: mix phx.server
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: MIX_ENV
        value: prod
      - key: PHX_HOST
        value: voice-bbs.onrender.com
